version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexus_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: nexus_dw
    ports:.
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nexus_net
    restart: always

volumes:
  pg_data:

networks:
  nexus_net:
    driver: bridge
